version: '3.9'

services:
  weaviate:
    image: semitechnologies/weaviate:1.25.3
    container_name: weaviate-dev
    ports:
      - '8080:8080'
      - '6060:6060'
    environment:
      QUERY_DEFAULTS_LIMIT: '25'
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      ENABLE_MODULES: 'bm25'
      DEFAULT_VECTORIZER_MODULE: 'none'
    volumes:
      - weaviate-data:/var/lib/weaviate

volumes:
  weaviate-data:
